version: '3.8'

services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: amsdbrest2024
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306" # Corrected port mapping for MySQL
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -prootpassword || exit 1"]
      interval: 10s
      retries: 10
    networks:
      - mynetwork

  backend:
    build:
      context: ../amsRest2024
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MYSQL_HOST: database
      MYSQL_DBNAME: amsdbrest2024
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    depends_on:
      database:
        condition: service_healthy
    networks:
      - mynetwork

  frontend:
    build:
      context: ../amsFront2024
      dockerfile: Dockerfile
      # args:
      #   API_URL: http://127.0.0.1:8080 # Change this value as needed
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mynetwork
    # env_file:
    #   - ../amsFront2024/.env


volumes:
  mysql_data:

networks:
  mynetwork: